---
- name: Deploy EC2 instance
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    region: us-east-1
    vpc_id: 
    subnet_id: 
    instance_type: t3.large
    image_id: ami-0778521d914d23bc1
    key_name: id_rsa
    security_group_ssh:
    security_group_minecraft:
    tag_name:
    target_group_arn :
    port:
    target_group_name :
    groupe_name : groupe-
  
  tasks:
    - name: Create EC2 instance
      ec2:
        key_name: "{{ key_name }}"
        groupe_name :
        group_id: "{{ security_group_ssh }}"
        group_id: "{{ security_group_minecraft }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image_id }}"
        wait: yes
        region: "{{ region }}"
        vpc_subnet_id: "{{ subnet_id }}"
        assign_public_ip: yes
        tags:
          Name: "{{ tag_name }}"
      register: ec2
    - name: Add instance to host group
      add_host:
        hostname: "{{ ec2.instance.public_ip }}"
        groupname: ec2_instances
    - name: Create Internet Gateway
      ec2_vpc_igw:
        state: present
        vpc_id: "{{ vpc_out.vpc.id }}"
    - name: Write inventory file
      include: inventory.yml
    - name: Ajouter l'instance EC2 au groupe d'échelle automatique
      autoscaling:
        name: "{{ group_name }}"
        min_size: "1"
        max_size: "1"
        desired_capacity: "1"
        launch_config_name: "{{ group_name }}-config"
        region: "{{ region }}"
        instance_ids: "{{ ec2.instances.id }}"
    - name: Create target group for load balancer
      elasticloadbalancingv2_target_group:
      state: present
      name: <target_group_name>
      protocol: TCP
      port: <port>
      vpc_id: <vpc_id>
    - name: Create listener for load balancer
      elasticloadbalancingv2_listener:
        state: present
        load_balancer_arn: <load_balancer_arn>
        protocol: TCP
        port: <port>
        default_action:
        type: forward
        target_group_arn: elasticloadbalancingv2_targetgroup
    - name: Register instance with target group
      elasticloadbalancingv2_target:
        state: present
        target_group_arn: elasticloadbalancingv2_targetgroup
        id: ec2
        port: <port>
        availability_zone: <region>