- name: Metrics Usage
  hosts: all
  become: yes

  tasks:
  - name: Check CPU usage
    cloudwatch_metric_alarm:
      state: present
      alarm_name: high-cpu-usage
      comparison_operator: GreaterThanThreshold
      evaluation_periods: 1
      metric_name: CPUUtilization
      namespace: AWS/EC2
      period: 60
      statistic: Average
      threshold: 70
      alarm_description: "Alarm when CPU usage exceeds 70% for 1 minute"
      alarm_actions: "loic.fermet@viacesi.fr"

  - name: Check RAM usage
    cloudwatch_metric_alarm:
      state: present
      alarm_name: high-ram-usage
      comparison_operator: GreaterThanThreshold
      evaluation_periods: 1
      metric_name: MemoryUtilization
      namespace: AWS/EC2
      period: 60  
      statistic: Average
      threshold: 70
      alarm_description: "Alarm when CPU usage exceeds 70% for 1 minute"
      alarm_actions: "loic.fermet@viacesi.fr"