---
- name: Deploy EC2 instance
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    region: us-east-1
    vpc_id: 
    subnet_id: 
    instance_type: t3.large
    image_id: ami-0778521d914d23bc1
    key_name: id_rsa
    security_group_ssh:
    security_group_minecraft:
    tag_name: 
  
  tasks:
    - name: Create EC2 instance
      ec2:
        key_name: "{{ key_name }}"
        group_id: "{{ security_group_ssh }}"
        group_id: "{{ security_group_minecraft }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image_id }}"
        wait: yes
        region: "{{ region }}"
        vpc_subnet_id: "{{ subnet_id }}"
        assign_public_ip: yes
        tags:
          Name: "{{ tag_name }}"
      register: ec2
    - name: Add instance to host group
      add_host:
        hostname: "{{ ec2.instance.public_ip }}"
        groupname: ec2_instances
    - name: Create Internet Gateway
      ec2_vpc_igw:
        state: present
        vpc_id: "{{ vpc_out.vpc.id }}"
    - name: Write inventory file
      include: inventory.yml