---
- hosts: serveur_minecraft
  become: yes
  vars:
    vpc: 
    port:
    group_name:
  tasks:
  - name: Create listener for load balancer
    elasticloadbalancingv2_listener:
      state: present
      load_balancer_arn: <load_balancer_arn>
      protocol: TCP
      port: <port>
      default_action:
        type: <default_action_type>
        target_group_arn: <target_group_arn>