- name: Install Minecraft
  hosts: all
  become: yes

  tasks:
  - name: "Update system"
    apt: 
      name: "*"
      state: latest
      update_cache: yes
  - name: Install java
    package:
      state: present
      name: java-1.8.0-openjdk-headless
  - name: Create group
    group:
      state: present
      name: "{{ minecraft.server.group }}"
  - name: Make the minecraft directory
    file:
      state: directory
      path: "/var/minecraft/server"
  - name: Create user
    user:
      state: present
      create_home: yes
      home: /var/minecraft/server/
      name: "minecraft"
      group: "minecraft"
  - name: Write eula
    copy:
      content: "eula=true"
      dest: "/var/minecraft/server/eula.txt"
      owner: "minecraft"
      group: "minecraft"



  - name: Create system service
        template:
          src: templates/minecraft.service
          dest: "/etc/systemd/system/minecraft.service"
          mode: 0644
      - name: Start minecraft service
        service:
          name: minecraft
          enabled: yes
          state: started